//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zaj04.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conference
    {
        public int Id { get; set; }
        public string AuthorFirstName { get; set; }
        public string AuthorLastName { get; set; }
        public string Email { get; set; }
        public string ArticleTitle { get; set; }
        public string ArticleAbstract { get; set; }
    }
}
